services:
  vllm_qwen3_32B:
    platform: linux/amd64
    image: vllm/vllm-openai:v0.10.0
    container_name: vllm_qwen3_32B
    ports:
      - ${LLM_API_PORT}:8000
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ipc: host
    volumes:
      - ${HUGGING_FACE_CACHE_DIR}:/root/.cache/huggingface
    command: >
      --port 8000
      --model Qwen/Qwen3-32B-AWQ
      --max-model-len 40960
      --gpu-memory-utilization 0.75
      --enable-auto-tool-choice
      --tool-call-parser hermes
      --tensor-parallel-size 2
      --enable-reasoning
      --reasoning-parser deepseek_r1