name: Build and Publish Docker Image
on:
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    publish:
        uses: DCC-BS/ci-workflows/.github/workflows/publish-docker.yml@7c802221337a90f2befc0a01c9b37e416395ae40 # v8
        secrets: inherit
        with:
            project_type: "python" # or "node"
            registry: ghcr.io
            image_name: ghcr.io/${{ github.repository }}
            context: .
            dockerfile: ./Dockerfile
            platforms: linux/amd64
            push: true
